# Generated by Django 6.0.2 on 2026-02-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="lifecycle",
            field=models.CharField(
                choices=[
                    ("Stable", "Estável"),
                    ("Viral", "Viral"),
                    ("Obsolete", "Obsoleto"),
                ],
                default="Stable",
                max_length=20,
                verbose_name="Ciclo de Vida",
            ),
        ),
    ]
